src/Entity/HoraireSettings.php
<?php

namespace App\Entity;

use App\Repository\HoraireSettingsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: HoraireSettingsRepository::class)]
class HoraireSettings
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    #[Assert\NotNull()]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $entree = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $ExitBreak = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $ReturnBreak = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $ExitWork = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEntree(): ?\DateTimeInterface
    {
        return $this->entree;
    }

    public function setEntree(\DateTimeInterface $entree): self
    {
        $this->entree = $entree;

        return $this;
    }

    public function getExitBreak(): ?\DateTimeInterface
    {
        return $this->ExitBreak;
    }

    public function setExitBreak(\DateTimeInterface $ExitBreak): self
    {
        $this->ExitBreak = $ExitBreak;

        return $this;
    }

    public function getReturnBreak(): ?\DateTimeInterface
    {
        return $this->ReturnBreak;
    }

    public function setReturnBreak(\DateTimeInterface $ReturnBreak): self
    {
        $this->ReturnBreak = $ReturnBreak;

        return $this;
    }

    public function getExitWork(): ?\DateTimeInterface
    {
        return $this->ExitWork;
    }

    public function setExitWork(\DateTimeInterface $ExitWork): self
    {
        $this->ExitWork = $ExitWork;

        return $this;
    }
}

src/Controller/HoraireSettingsController.php
<?php

namespace App\Controller;

use App\Entity\HoraireSettings;
use App\Form\HoraireType;
use App\Repository\HoraireSettingsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HoraireSettingsController extends AbstractController
{
    /**
     * function default findAll
     */
    #[Route('/horaire/settings', name: 'app_horaire_settings', methods: ['GET'])]
    public function index(HoraireSettingsRepository $repository, PaginatorInterface $paginator, Request $request): Response
    {
        $horaire = $paginator->paginate(
            $repository->findAll(), /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            5 /*limit per page*/
        );
        //$horaire = $repository->findAll();
        //dd($horaire);
        return $this->render('pages/horaire_settings/index.html.twig', [
          "horaires" => $horaire
        ]);
    }

    #[Route('/horaire/settings/new', name: 'horaire_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $manager): Response 
    {
        $horaireSettings = new HoraireSettings();
        $form = $this->createForm(HoraireType::class, $horaireSettings);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $horaireSettgs = $form->getData();
            $manager->persist($horaireSettgs);
            $manager->flush();
            $this->addFlash('success', 'Horaire crée avec success!!');
            return $this->redirectToRoute('app_horaire_settings');
        } else {
            $this->addFlash('warning', 'Horaire envoyé contient des erreurs');
        }
        return $this->render('pages/horaire_settings/new.html.twig',
           [
            'form' => $form->createView()
           ]
        );
    }
 
    #[Route('/horaire/settings/edit/{id}', name: 'horaire_edit', methods: ['GET', 'POST'])]
    public function edit(HoraireSettings $horaireSettings, Request $request, EntityManagerInterface $manager): Response
    {
        $form = $this->createForm(HoraireType::class, $horaireSettings);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $horaireSettgs = $form->getData();
            $manager->persist($horaireSettgs);
            $manager->flush();
            $this->addFlash('success', 'Horaire modifié avec success!!');
            return $this->redirectToRoute('app_horaire_settings');
        } else {
            $this->addFlash('warning', 'Horaire envoyé contient des erreurs');
        }
        return $this->render('pages/horaire_settings/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/horaire/settings/delete/{id}', name: 'horaire_delete', methods: ['GET'])]
    public function delete(HoraireSettings $horaireSettings, EntityManagerInterface $manager) : Response
    {
        if (!$horaireSettings) {
            $this->addFlash('success', 'Horaire with this id not exist!!');
            return $this->redirectToRoute('app_horaire_settings');
        }
        $manager->remove($horaireSettings);
        $manager->flush();
        $this->addFlash('success', 'Horaire supprimée avec success!!');
        return $this->redirectToRoute('app_horaire_settings');
    }
}

templates/pages/horaire_settings/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}
    Edit Horaire
{% endblock %}

{% block body %}
    <div class="container">
      <h2 class="mt-4">Modification d'un Horaire</h2>
      
      {{form_start(form)}}
      <div class="form-group">
        {{form_label(form.name)}}
        {{form_widget(form.name)}}
        <div class="form-error">{{form_errors(form.name)}}</div>
      </div>
      <div class="form-group">
        {{form_label(form.description)}}
        {{form_widget(form.description)}}
        <div class="form-error">{{form_errors(form.description)}}</div>
      </div>
      <div class="form-group">
        {{form_label(form.entree)}}
        {{form_widget(form.entree)}}
        <div class="form-error">{{form_errors(form.entree)}}</div>
      </div>
      <div class="form-group">
        {{form_label(form.ExitBreak)}}
        {{form_widget(form.ExitBreak)}}
        <div class="form-error">{{form_errors(form.ExitBreak)}}</div>
      </div>
      <div class="form-group">
        {{form_label(form.ReturnBreak)}}
        {{form_widget(form.ReturnBreak)}}
        <div class="form-error">{{form_errors(form.ReturnBreak)}}</div>
      </div>
      <div class="form-group">
        {{form_label(form.ExitWork)}}
        {{form_widget(form.ExitWork)}}
        <div class="form-error">{{form_errors(form.ExitWork)}}</div>
      </div>
      <div class="form-group">
        {{form_row(form.submit)}}
      </div>
      {{form_end(form)}}
    </div>
{% endblock %}

templates/pages/horaire_settings/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Horaires Settings{% endblock %}

{% block body %}

<div class="container mt-4">
  <h2>Horaires des Employes</h2>
  <div class="count">
    {{ horaires.getTotalItemCount }}
  </div>
    <a href="{{path('horaire_new')}}" class="btn btn-secondary">Nouvel Horaire</a>
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">{{message}}</div>
    {% endfor %}
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">{{ knp_pagination_sortable(horaires, 'Id', 'a.id') }}</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Entree</th>
        <th scope="col">ExitBreak</th>
        <th scope="col">ReturnBreak</th>
        <th scope="col">ExitWork</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
        {% for horaire in horaires %}
            <tr class="table-primary">
              <th scope="row">{{horaire.id}}</th>
              <th scope="row">{{horaire.name}}</th>
              <th scope="row">{{horaire.description}}</th>
              <th scope="row">{{horaire.entree | date("H:i:s")}}</th>
              <th scope="row">{{horaire.exitBreak | date("H:i:s")}}</th>
              <th scope="row">{{horaire.returnBreak | date("H:i:s")}}</th>
              <th scope="row">{{horaire.exitWork | date("H:i:s")}}</th>
              <th scope="row"><a href="{{path('horaire_edit', {id: horaire.id})}}">Update</a></th>
              <th scope="row"><a href="{{path('horaire_delete', {id: horaire.id})}}">Delete</a></th>
            </tr>
        {% endfor %}
    </tbody>
  </table>
  {# display navigation #}
<div class="navigation">
    {{ knp_pagination_render(horaires) }}
</div>
</div>
{% endblock %}

templates/pages/horaire_settings/new.html.twig
{% extends "base.html.twig" %}

{% block title %}
    New Horaire
{% endblock %}

{% block body %}
    <div class="container">
      <h2 class="mt-4">Création d'une Horaire</h2>
      
      {{form_start(form)}}
      <div class="form-group">
        {{form_label(form.name)}}
        {{form_widget(form.name)}}
        <div class="form-error">{{form_errors(form.name)}}</div>
      </div>
      <div class="form-group">
        {{form_label(form.description)}}
        {{form_widget(form.description)}}
        <div class="form-error">{{form_errors(form.description)}}</div>
      </div>
      <div class="form-group">
        {{form_label(form.entree)}}
        {{form_widget(form.entree)}}
        <div class="form-error">{{form_errors(form.entree)}}</div>
      </div>
      <div class="form-group">
        {{form_label(form.ExitBreak)}}
        {{form_widget(form.ExitBreak)}}
        <div class="form-error">{{form_errors(form.ExitBreak)}}</div>
      </div>
      <div class="form-group">
        {{form_label(form.ReturnBreak)}}
        {{form_widget(form.ReturnBreak)}}
        <div class="form-error">{{form_errors(form.ReturnBreak)}}</div>
      </div>
      <div class="form-group">
        {{form_label(form.ExitWork)}}
        {{form_widget(form.ExitWork)}}
        <div class="form-error">{{form_errors(form.ExitWork)}}</div>
      </div>
      <div class="form-group">
        {{form_row(form.submit)}}
      </div>
      {{form_end(form)}}
    </div>
{% endblock %}